// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast_info.proto

package org.led.bigdata.proto.bmc;

public final class Broadcast {
  private Broadcast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BroadcastInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serviceId = 1;
    /**
     * <code>required string serviceId = 1;</code>
     */
    boolean hasServiceId();
    /**
     * <code>required string serviceId = 1;</code>
     */
    java.lang.String getServiceId();
    /**
     * <code>required string serviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    // required string broadcastId = 2;
    /**
     * <code>required string broadcastId = 2;</code>
     */
    boolean hasBroadcastId();
    /**
     * <code>required string broadcastId = 2;</code>
     */
    java.lang.String getBroadcastId();
    /**
     * <code>required string broadcastId = 2;</code>
     */
    com.google.protobuf.ByteString
        getBroadcastIdBytes();

    // required string tmgi = 3;
    /**
     * <code>required string tmgi = 3;</code>
     */
    boolean hasTmgi();
    /**
     * <code>required string tmgi = 3;</code>
     */
    java.lang.String getTmgi();
    /**
     * <code>required string tmgi = 3;</code>
     */
    com.google.protobuf.ByteString
        getTmgiBytes();

    // required string startTime = 4;
    /**
     * <code>required string startTime = 4;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required string startTime = 4;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>required string startTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    // required string stopTime = 5;
    /**
     * <code>required string stopTime = 5;</code>
     */
    boolean hasStopTime();
    /**
     * <code>required string stopTime = 5;</code>
     */
    java.lang.String getStopTime();
    /**
     * <code>required string stopTime = 5;</code>
     */
    com.google.protobuf.ByteString
        getStopTimeBytes();

    // required string type = 6;
    /**
     * <code>required string type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 6;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 6;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    boolean hasAdfInfo();
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo getAdfInfo();
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder getAdfInfoOrBuilder();
  }
  /**
   * Protobuf type {@code bmc.BroadcastInfo}
   */
  public static final class BroadcastInfo extends
      com.google.protobuf.GeneratedMessage
      implements BroadcastInfoOrBuilder {
    // Use BroadcastInfo.newBuilder() to construct.
    private BroadcastInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BroadcastInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BroadcastInfo defaultInstance;
    public static BroadcastInfo getDefaultInstance() {
      return defaultInstance;
    }

    public BroadcastInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              broadcastId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tmgi_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              startTime_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              stopTime_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              type_ = input.readBytes();
              break;
            }
            case 58: {
              org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = adfInfo_.toBuilder();
              }
              adfInfo_ = input.readMessage(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(adfInfo_);
                adfInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.class, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<BroadcastInfo> PARSER =
        new com.google.protobuf.AbstractParser<BroadcastInfo>() {
      public BroadcastInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastInfo> getParserForType() {
      return PARSER;
    }

    public interface AdfInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string ip = 1;
      /**
       * <code>required string ip = 1;</code>
       */
      boolean hasIp();
      /**
       * <code>required string ip = 1;</code>
       */
      java.lang.String getIp();
      /**
       * <code>required string ip = 1;</code>
       */
      com.google.protobuf.ByteString
          getIpBytes();

      // required string port = 2;
      /**
       * <code>required string port = 2;</code>
       */
      boolean hasPort();
      /**
       * <code>required string port = 2;</code>
       */
      java.lang.String getPort();
      /**
       * <code>required string port = 2;</code>
       */
      com.google.protobuf.ByteString
          getPortBytes();

      // required string root = 3;
      /**
       * <code>required string root = 3;</code>
       */
      boolean hasRoot();
      /**
       * <code>required string root = 3;</code>
       */
      java.lang.String getRoot();
      /**
       * <code>required string root = 3;</code>
       */
      com.google.protobuf.ByteString
          getRootBytes();
    }
    /**
     * Protobuf type {@code bmc.BroadcastInfo.AdfInfo}
     */
    public static final class AdfInfo extends
        com.google.protobuf.GeneratedMessage
        implements AdfInfoOrBuilder {
      // Use AdfInfo.newBuilder() to construct.
      private AdfInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private AdfInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final AdfInfo defaultInstance;
      public static AdfInfo getDefaultInstance() {
        return defaultInstance;
      }

      public AdfInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private AdfInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                ip_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                port_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                root_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_AdfInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_AdfInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.class, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<AdfInfo> PARSER =
          new com.google.protobuf.AbstractParser<AdfInfo>() {
        public AdfInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AdfInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<AdfInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string ip = 1;
      public static final int IP_FIELD_NUMBER = 1;
      private java.lang.Object ip_;
      /**
       * <code>required string ip = 1;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string port = 2;
      public static final int PORT_FIELD_NUMBER = 2;
      private java.lang.Object port_;
      /**
       * <code>required string port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string port = 2;</code>
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            port_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string port = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string root = 3;
      public static final int ROOT_FIELD_NUMBER = 3;
      private java.lang.Object root_;
      /**
       * <code>required string root = 3;</code>
       */
      public boolean hasRoot() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string root = 3;</code>
       */
      public java.lang.String getRoot() {
        java.lang.Object ref = root_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            root_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string root = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRootBytes() {
        java.lang.Object ref = root_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          root_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        ip_ = "";
        port_ = "";
        root_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasIp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasRoot()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIpBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPortBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getRootBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIpBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPortBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getRootBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code bmc.BroadcastInfo.AdfInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_AdfInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_AdfInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.class, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder.class);
        }

        // Construct using org.led.bmc.Broadcast.BroadcastInfo.AdfInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          ip_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          port_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          root_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_AdfInfo_descriptor;
        }

        public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo getDefaultInstanceForType() {
          return org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance();
        }

        public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo build() {
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo buildPartial() {
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo result = new org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ip_ = ip_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.port_ = port_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.root_ = root_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo) {
            return mergeFrom((org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo other) {
          if (other == org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance()) return this;
          if (other.hasIp()) {
            bitField0_ |= 0x00000001;
            ip_ = other.ip_;
            onChanged();
          }
          if (other.hasPort()) {
            bitField0_ |= 0x00000002;
            port_ = other.port_;
            onChanged();
          }
          if (other.hasRoot()) {
            bitField0_ |= 0x00000004;
            root_ = other.root_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasIp()) {
            
            return false;
          }
          if (!hasPort()) {
            
            return false;
          }
          if (!hasRoot()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string ip = 1;
        private java.lang.Object ip_ = "";
        /**
         * <code>required string ip = 1;</code>
         */
        public boolean hasIp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string ip = 1;</code>
         */
        public java.lang.String getIp() {
          java.lang.Object ref = ip_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            ip_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string ip = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIpBytes() {
          java.lang.Object ref = ip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string ip = 1;</code>
         */
        public Builder setIp(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          ip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string ip = 1;</code>
         */
        public Builder clearIp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ip_ = getDefaultInstance().getIp();
          onChanged();
          return this;
        }
        /**
         * <code>required string ip = 1;</code>
         */
        public Builder setIpBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          ip_ = value;
          onChanged();
          return this;
        }

        // required string port = 2;
        private java.lang.Object port_ = "";
        /**
         * <code>required string port = 2;</code>
         */
        public boolean hasPort() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string port = 2;</code>
         */
        public java.lang.String getPort() {
          java.lang.Object ref = port_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            port_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string port = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPortBytes() {
          java.lang.Object ref = port_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            port_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string port = 2;</code>
         */
        public Builder setPort(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string port = 2;</code>
         */
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = getDefaultInstance().getPort();
          onChanged();
          return this;
        }
        /**
         * <code>required string port = 2;</code>
         */
        public Builder setPortBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          port_ = value;
          onChanged();
          return this;
        }

        // required string root = 3;
        private java.lang.Object root_ = "";
        /**
         * <code>required string root = 3;</code>
         */
        public boolean hasRoot() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string root = 3;</code>
         */
        public java.lang.String getRoot() {
          java.lang.Object ref = root_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            root_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string root = 3;</code>
         */
        public com.google.protobuf.ByteString
            getRootBytes() {
          java.lang.Object ref = root_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            root_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string root = 3;</code>
         */
        public Builder setRoot(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          root_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string root = 3;</code>
         */
        public Builder clearRoot() {
          bitField0_ = (bitField0_ & ~0x00000004);
          root_ = getDefaultInstance().getRoot();
          onChanged();
          return this;
        }
        /**
         * <code>required string root = 3;</code>
         */
        public Builder setRootBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          root_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:bmc.BroadcastInfo.AdfInfo)
      }

      static {
        defaultInstance = new AdfInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:bmc.BroadcastInfo.AdfInfo)
    }

    private int bitField0_;
    // required string serviceId = 1;
    public static final int SERVICEID_FIELD_NUMBER = 1;
    private java.lang.Object serviceId_;
    /**
     * <code>required string serviceId = 1;</code>
     */
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serviceId = 1;</code>
     */
    public java.lang.String getServiceId() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string broadcastId = 2;
    public static final int BROADCASTID_FIELD_NUMBER = 2;
    private java.lang.Object broadcastId_;
    /**
     * <code>required string broadcastId = 2;</code>
     */
    public boolean hasBroadcastId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string broadcastId = 2;</code>
     */
    public java.lang.String getBroadcastId() {
      java.lang.Object ref = broadcastId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          broadcastId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string broadcastId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBroadcastIdBytes() {
      java.lang.Object ref = broadcastId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        broadcastId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string tmgi = 3;
    public static final int TMGI_FIELD_NUMBER = 3;
    private java.lang.Object tmgi_;
    /**
     * <code>required string tmgi = 3;</code>
     */
    public boolean hasTmgi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string tmgi = 3;</code>
     */
    public java.lang.String getTmgi() {
      java.lang.Object ref = tmgi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tmgi_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tmgi = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTmgiBytes() {
      java.lang.Object ref = tmgi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tmgi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string startTime = 4;
    public static final int STARTTIME_FIELD_NUMBER = 4;
    private java.lang.Object startTime_;
    /**
     * <code>required string startTime = 4;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string startTime = 4;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string startTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string stopTime = 5;
    public static final int STOPTIME_FIELD_NUMBER = 5;
    private java.lang.Object stopTime_;
    /**
     * <code>required string stopTime = 5;</code>
     */
    public boolean hasStopTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string stopTime = 5;</code>
     */
    public java.lang.String getStopTime() {
      java.lang.Object ref = stopTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stopTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stopTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStopTimeBytes() {
      java.lang.Object ref = stopTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private java.lang.Object type_;
    /**
     * <code>required string type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string type = 6;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;
    public static final int ADFINFO_FIELD_NUMBER = 7;
    private org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo adfInfo_;
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    public boolean hasAdfInfo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo getAdfInfo() {
      return adfInfo_;
    }
    /**
     * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
     */
    public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder getAdfInfoOrBuilder() {
      return adfInfo_;
    }

    private void initFields() {
      serviceId_ = "";
      broadcastId_ = "";
      tmgi_ = "";
      startTime_ = "";
      stopTime_ = "";
      type_ = "";
      adfInfo_ = org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBroadcastId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTmgi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStopTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAdfInfo()) {
        if (!getAdfInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBroadcastIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTmgiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStopTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, adfInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBroadcastIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTmgiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStopTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, adfInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bmc.BroadcastInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.led.bigdata.proto.bmc.Broadcast.BroadcastInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.class, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.Builder.class);
      }

      // Construct using org.led.bmc.Broadcast.BroadcastInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAdfInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        broadcastId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tmgi_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        stopTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (adfInfoBuilder_ == null) {
          adfInfo_ = org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance();
        } else {
          adfInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.led.bigdata.proto.bmc.Broadcast.internal_static_bmc_BroadcastInfo_descriptor;
      }

      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo getDefaultInstanceForType() {
        return org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.getDefaultInstance();
      }

      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo build() {
        org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo buildPartial() {
        org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo result = new org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceId_ = serviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.broadcastId_ = broadcastId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tmgi_ = tmgi_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.stopTime_ = stopTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (adfInfoBuilder_ == null) {
          result.adfInfo_ = adfInfo_;
        } else {
          result.adfInfo_ = adfInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo) {
          return mergeFrom((org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo other) {
        if (other == org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.getDefaultInstance()) return this;
        if (other.hasServiceId()) {
          bitField0_ |= 0x00000001;
          serviceId_ = other.serviceId_;
          onChanged();
        }
        if (other.hasBroadcastId()) {
          bitField0_ |= 0x00000002;
          broadcastId_ = other.broadcastId_;
          onChanged();
        }
        if (other.hasTmgi()) {
          bitField0_ |= 0x00000004;
          tmgi_ = other.tmgi_;
          onChanged();
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000008;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasStopTime()) {
          bitField0_ |= 0x00000010;
          stopTime_ = other.stopTime_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000020;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasAdfInfo()) {
          mergeAdfInfo(other.getAdfInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceId()) {
          
          return false;
        }
        if (!hasBroadcastId()) {
          
          return false;
        }
        if (!hasTmgi()) {
          
          return false;
        }
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasStopTime()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (hasAdfInfo()) {
          if (!getAdfInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serviceId = 1;
      private java.lang.Object serviceId_ = "";
      /**
       * <code>required string serviceId = 1;</code>
       */
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serviceId = 1;</code>
       */
      public java.lang.String getServiceId() {
        java.lang.Object ref = serviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        java.lang.Object ref = serviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceId = 1;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceId = 1;</code>
       */
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceId_ = getDefaultInstance().getServiceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceId = 1;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceId_ = value;
        onChanged();
        return this;
      }

      // required string broadcastId = 2;
      private java.lang.Object broadcastId_ = "";
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public boolean hasBroadcastId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public java.lang.String getBroadcastId() {
        java.lang.Object ref = broadcastId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          broadcastId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBroadcastIdBytes() {
        java.lang.Object ref = broadcastId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          broadcastId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public Builder setBroadcastId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        broadcastId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public Builder clearBroadcastId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        broadcastId_ = getDefaultInstance().getBroadcastId();
        onChanged();
        return this;
      }
      /**
       * <code>required string broadcastId = 2;</code>
       */
      public Builder setBroadcastIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        broadcastId_ = value;
        onChanged();
        return this;
      }

      // required string tmgi = 3;
      private java.lang.Object tmgi_ = "";
      /**
       * <code>required string tmgi = 3;</code>
       */
      public boolean hasTmgi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string tmgi = 3;</code>
       */
      public java.lang.String getTmgi() {
        java.lang.Object ref = tmgi_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tmgi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tmgi = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTmgiBytes() {
        java.lang.Object ref = tmgi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tmgi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tmgi = 3;</code>
       */
      public Builder setTmgi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tmgi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tmgi = 3;</code>
       */
      public Builder clearTmgi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tmgi_ = getDefaultInstance().getTmgi();
        onChanged();
        return this;
      }
      /**
       * <code>required string tmgi = 3;</code>
       */
      public Builder setTmgiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tmgi_ = value;
        onChanged();
        return this;
      }

      // required string startTime = 4;
      private java.lang.Object startTime_ = "";
      /**
       * <code>required string startTime = 4;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string startTime = 4;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string startTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string startTime = 4;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 4;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 4;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        startTime_ = value;
        onChanged();
        return this;
      }

      // required string stopTime = 5;
      private java.lang.Object stopTime_ = "";
      /**
       * <code>required string stopTime = 5;</code>
       */
      public boolean hasStopTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string stopTime = 5;</code>
       */
      public java.lang.String getStopTime() {
        java.lang.Object ref = stopTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stopTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stopTime = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStopTimeBytes() {
        java.lang.Object ref = stopTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stopTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stopTime = 5;</code>
       */
      public Builder setStopTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        stopTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string stopTime = 5;</code>
       */
      public Builder clearStopTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        stopTime_ = getDefaultInstance().getStopTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string stopTime = 5;</code>
       */
      public Builder setStopTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        stopTime_ = value;
        onChanged();
        return this;
      }

      // required string type = 6;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string type = 6;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 6;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 6;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }

      // optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;
      private org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo adfInfo_ = org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder> adfInfoBuilder_;
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public boolean hasAdfInfo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo getAdfInfo() {
        if (adfInfoBuilder_ == null) {
          return adfInfo_;
        } else {
          return adfInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public Builder setAdfInfo(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo value) {
        if (adfInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          adfInfo_ = value;
          onChanged();
        } else {
          adfInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public Builder setAdfInfo(
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder builderForValue) {
        if (adfInfoBuilder_ == null) {
          adfInfo_ = builderForValue.build();
          onChanged();
        } else {
          adfInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public Builder mergeAdfInfo(org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo value) {
        if (adfInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              adfInfo_ != org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance()) {
            adfInfo_ =
              org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.newBuilder(adfInfo_).mergeFrom(value).buildPartial();
          } else {
            adfInfo_ = value;
          }
          onChanged();
        } else {
          adfInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public Builder clearAdfInfo() {
        if (adfInfoBuilder_ == null) {
          adfInfo_ = org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.getDefaultInstance();
          onChanged();
        } else {
          adfInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder getAdfInfoBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getAdfInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      public org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder getAdfInfoOrBuilder() {
        if (adfInfoBuilder_ != null) {
          return adfInfoBuilder_.getMessageOrBuilder();
        } else {
          return adfInfo_;
        }
      }
      /**
       * <code>optional .bmc.BroadcastInfo.AdfInfo adfInfo = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder> 
          getAdfInfoFieldBuilder() {
        if (adfInfoBuilder_ == null) {
          adfInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfo.Builder, org.led.bigdata.proto.bmc.Broadcast.BroadcastInfo.AdfInfoOrBuilder>(
                  adfInfo_,
                  getParentForChildren(),
                  isClean());
          adfInfo_ = null;
        }
        return adfInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:bmc.BroadcastInfo)
    }

    static {
      defaultInstance = new BroadcastInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bmc.BroadcastInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bmc_BroadcastInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bmc_BroadcastInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bmc_BroadcastInfo_AdfInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bmc_BroadcastInfo_AdfInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024broadcast_info.proto\022\003bmc\"\330\001\n\rBroadcas" +
      "tInfo\022\021\n\tserviceId\030\001 \002(\t\022\023\n\013broadcastId\030" +
      "\002 \002(\t\022\014\n\004tmgi\030\003 \002(\t\022\021\n\tstartTime\030\004 \002(\t\022\020" +
      "\n\010stopTime\030\005 \002(\t\022\014\n\004type\030\006 \002(\t\022+\n\007adfInf" +
      "o\030\007 \001(\0132\032.bmc.BroadcastInfo.AdfInfo\0321\n\007A" +
      "dfInfo\022\n\n\002ip\030\001 \002(\t\022\014\n\004port\030\002 \002(\t\022\014\n\004root" +
      "\030\003 \002(\tB\030\n\013org.led.bmcB\tBroadcast"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bmc_BroadcastInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bmc_BroadcastInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bmc_BroadcastInfo_descriptor,
              new java.lang.String[] { "ServiceId", "BroadcastId", "Tmgi", "StartTime", "StopTime", "Type", "AdfInfo", });
          internal_static_bmc_BroadcastInfo_AdfInfo_descriptor =
            internal_static_bmc_BroadcastInfo_descriptor.getNestedTypes().get(0);
          internal_static_bmc_BroadcastInfo_AdfInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bmc_BroadcastInfo_AdfInfo_descriptor,
              new java.lang.String[] { "Ip", "Port", "Root", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
