// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmc.proto

package org.led.tools.proto.bmc;

public final class BmcInfo {
  private BmcInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BmcOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string ip = 2;
    /**
     * <code>required string ip = 2;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // required string port = 3;
    /**
     * <code>required string port = 3;</code>
     */
    boolean hasPort();
    /**
     * <code>required string port = 3;</code>
     */
    java.lang.String getPort();
    /**
     * <code>required string port = 3;</code>
     */
    com.google.protobuf.ByteString
        getPortBytes();

    // optional string desc = 4;
    /**
     * <code>optional string desc = 4;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // repeated .bmc.Bmc.Bdc bdc = 5;
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> 
        getBdcList();
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc getBdc(int index);
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    int getBdcCount();
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    java.util.List<? extends org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder> 
        getBdcOrBuilderList();
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder getBdcOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bmc.Bmc}
   */
  public static final class Bmc extends
      com.google.protobuf.GeneratedMessage
      implements BmcOrBuilder {
    // Use Bmc.newBuilder() to construct.
    private Bmc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Bmc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Bmc defaultInstance;
    public static Bmc getDefaultInstance() {
      return defaultInstance;
    }

    public Bmc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Bmc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ip_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              port_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              desc_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                bdc_ = new java.util.ArrayList<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc>();
                mutable_bitField0_ |= 0x00000010;
              }
              bdc_.add(input.readMessage(org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          bdc_ = java.util.Collections.unmodifiableList(bdc_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.led.tools.proto.bmc.BmcInfo.Bmc.class, org.led.tools.proto.bmc.BmcInfo.Bmc.Builder.class);
    }

    public static com.google.protobuf.Parser<Bmc> PARSER =
        new com.google.protobuf.AbstractParser<Bmc>() {
      public Bmc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bmc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Bmc> getParserForType() {
      return PARSER;
    }

    public interface BdcOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required string ip = 2;
      /**
       * <code>required string ip = 2;</code>
       */
      boolean hasIp();
      /**
       * <code>required string ip = 2;</code>
       */
      java.lang.String getIp();
      /**
       * <code>required string ip = 2;</code>
       */
      com.google.protobuf.ByteString
          getIpBytes();

      // required string port = 3;
      /**
       * <code>required string port = 3;</code>
       */
      boolean hasPort();
      /**
       * <code>required string port = 3;</code>
       */
      java.lang.String getPort();
      /**
       * <code>required string port = 3;</code>
       */
      com.google.protobuf.ByteString
          getPortBytes();

      // optional string desc = 4;
      /**
       * <code>optional string desc = 4;</code>
       */
      boolean hasDesc();
      /**
       * <code>optional string desc = 4;</code>
       */
      java.lang.String getDesc();
      /**
       * <code>optional string desc = 4;</code>
       */
      com.google.protobuf.ByteString
          getDescBytes();
    }
    /**
     * Protobuf type {@code bmc.Bmc.Bdc}
     */
    public static final class Bdc extends
        com.google.protobuf.GeneratedMessage
        implements BdcOrBuilder {
      // Use Bdc.newBuilder() to construct.
      private Bdc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Bdc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Bdc defaultInstance;
      public static Bdc getDefaultInstance() {
        return defaultInstance;
      }

      public Bdc getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Bdc(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                ip_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                port_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                desc_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_Bdc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_Bdc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.class, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder.class);
      }

      public static com.google.protobuf.Parser<Bdc> PARSER =
          new com.google.protobuf.AbstractParser<Bdc>() {
        public Bdc parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bdc(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Bdc> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string ip = 2;
      public static final int IP_FIELD_NUMBER = 2;
      private java.lang.Object ip_;
      /**
       * <code>required string ip = 2;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string port = 3;
      public static final int PORT_FIELD_NUMBER = 3;
      private java.lang.Object port_;
      /**
       * <code>required string port = 3;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string port = 3;</code>
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            port_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string port = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string desc = 4;
      public static final int DESC_FIELD_NUMBER = 4;
      private java.lang.Object desc_;
      /**
       * <code>optional string desc = 4;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        name_ = "";
        ip_ = "";
        port_ = "";
        desc_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getIpBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getPortBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getDescBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getIpBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getPortBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getDescBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code bmc.Bmc.Bdc}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_Bdc_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_Bdc_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.class, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder.class);
        }

        // Construct using org.led.bmc.BmcInfo.Bmc.Bdc.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          ip_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          desc_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_Bdc_descriptor;
        }

        public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc getDefaultInstanceForType() {
          return org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.getDefaultInstance();
        }

        public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc build() {
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc buildPartial() {
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc result = new org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.ip_ = ip_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.port_ = port_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.desc_ = desc_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc) {
            return mergeFrom((org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc other) {
          if (other == org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasIp()) {
            bitField0_ |= 0x00000002;
            ip_ = other.ip_;
            onChanged();
          }
          if (other.hasPort()) {
            bitField0_ |= 0x00000004;
            port_ = other.port_;
            onChanged();
          }
          if (other.hasDesc()) {
            bitField0_ |= 0x00000008;
            desc_ = other.desc_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasIp()) {
            
            return false;
          }
          if (!hasPort()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required string ip = 2;
        private java.lang.Object ip_ = "";
        /**
         * <code>required string ip = 2;</code>
         */
        public boolean hasIp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string ip = 2;</code>
         */
        public java.lang.String getIp() {
          java.lang.Object ref = ip_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            ip_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string ip = 2;</code>
         */
        public com.google.protobuf.ByteString
            getIpBytes() {
          java.lang.Object ref = ip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string ip = 2;</code>
         */
        public Builder setIp(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string ip = 2;</code>
         */
        public Builder clearIp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          ip_ = getDefaultInstance().getIp();
          onChanged();
          return this;
        }
        /**
         * <code>required string ip = 2;</code>
         */
        public Builder setIpBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ip_ = value;
          onChanged();
          return this;
        }

        // required string port = 3;
        private java.lang.Object port_ = "";
        /**
         * <code>required string port = 3;</code>
         */
        public boolean hasPort() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string port = 3;</code>
         */
        public java.lang.String getPort() {
          java.lang.Object ref = port_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            port_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string port = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPortBytes() {
          java.lang.Object ref = port_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            port_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string port = 3;</code>
         */
        public Builder setPort(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string port = 3;</code>
         */
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000004);
          port_ = getDefaultInstance().getPort();
          onChanged();
          return this;
        }
        /**
         * <code>required string port = 3;</code>
         */
        public Builder setPortBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          port_ = value;
          onChanged();
          return this;
        }

        // optional string desc = 4;
        private java.lang.Object desc_ = "";
        /**
         * <code>optional string desc = 4;</code>
         */
        public boolean hasDesc() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string desc = 4;</code>
         */
        public java.lang.String getDesc() {
          java.lang.Object ref = desc_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            desc_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string desc = 4;</code>
         */
        public com.google.protobuf.ByteString
            getDescBytes() {
          java.lang.Object ref = desc_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            desc_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string desc = 4;</code>
         */
        public Builder setDesc(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          desc_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string desc = 4;</code>
         */
        public Builder clearDesc() {
          bitField0_ = (bitField0_ & ~0x00000008);
          desc_ = getDefaultInstance().getDesc();
          onChanged();
          return this;
        }
        /**
         * <code>optional string desc = 4;</code>
         */
        public Builder setDescBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          desc_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:bmc.Bmc.Bdc)
      }

      static {
        defaultInstance = new Bdc(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:bmc.Bmc.Bdc)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ip = 2;
    public static final int IP_FIELD_NUMBER = 2;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 2;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string port = 3;
    public static final int PORT_FIELD_NUMBER = 3;
    private java.lang.Object port_;
    /**
     * <code>required string port = 3;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string port = 3;</code>
     */
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          port_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string port = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string desc = 4;
    public static final int DESC_FIELD_NUMBER = 4;
    private java.lang.Object desc_;
    /**
     * <code>optional string desc = 4;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .bmc.Bmc.Bdc bdc = 5;
    public static final int BDC_FIELD_NUMBER = 5;
    private java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> bdc_;
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    public java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> getBdcList() {
      return bdc_;
    }
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    public java.util.List<? extends org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder> 
        getBdcOrBuilderList() {
      return bdc_;
    }
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    public int getBdcCount() {
      return bdc_.size();
    }
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc getBdc(int index) {
      return bdc_.get(index);
    }
    /**
     * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
     */
    public org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder getBdcOrBuilder(
        int index) {
      return bdc_.get(index);
    }

    private void initFields() {
      name_ = "";
      ip_ = "";
      port_ = "";
      desc_ = "";
      bdc_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBdcCount(); i++) {
        if (!getBdc(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPortBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescBytes());
      }
      for (int i = 0; i < bdc_.size(); i++) {
        output.writeMessage(5, bdc_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPortBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescBytes());
      }
      for (int i = 0; i < bdc_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, bdc_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.led.tools.proto.bmc.BmcInfo.Bmc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.led.tools.proto.bmc.BmcInfo.Bmc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bmc.Bmc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.led.tools.proto.bmc.BmcInfo.BmcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.led.tools.proto.bmc.BmcInfo.Bmc.class, org.led.tools.proto.bmc.BmcInfo.Bmc.Builder.class);
      }

      // Construct using org.led.bmc.BmcInfo.Bmc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBdcFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (bdcBuilder_ == null) {
          bdc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          bdcBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.led.tools.proto.bmc.BmcInfo.internal_static_bmc_Bmc_descriptor;
      }

      public org.led.tools.proto.bmc.BmcInfo.Bmc getDefaultInstanceForType() {
        return org.led.tools.proto.bmc.BmcInfo.Bmc.getDefaultInstance();
      }

      public org.led.tools.proto.bmc.BmcInfo.Bmc build() {
        org.led.tools.proto.bmc.BmcInfo.Bmc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.led.tools.proto.bmc.BmcInfo.Bmc buildPartial() {
        org.led.tools.proto.bmc.BmcInfo.Bmc result = new org.led.tools.proto.bmc.BmcInfo.Bmc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.desc_ = desc_;
        if (bdcBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            bdc_ = java.util.Collections.unmodifiableList(bdc_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.bdc_ = bdc_;
        } else {
          result.bdc_ = bdcBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.led.tools.proto.bmc.BmcInfo.Bmc) {
          return mergeFrom((org.led.tools.proto.bmc.BmcInfo.Bmc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.led.tools.proto.bmc.BmcInfo.Bmc other) {
        if (other == org.led.tools.proto.bmc.BmcInfo.Bmc.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000002;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          bitField0_ |= 0x00000004;
          port_ = other.port_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000008;
          desc_ = other.desc_;
          onChanged();
        }
        if (bdcBuilder_ == null) {
          if (!other.bdc_.isEmpty()) {
            if (bdc_.isEmpty()) {
              bdc_ = other.bdc_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureBdcIsMutable();
              bdc_.addAll(other.bdc_);
            }
            onChanged();
          }
        } else {
          if (!other.bdc_.isEmpty()) {
            if (bdcBuilder_.isEmpty()) {
              bdcBuilder_.dispose();
              bdcBuilder_ = null;
              bdc_ = other.bdc_;
              bitField0_ = (bitField0_ & ~0x00000010);
              bdcBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBdcFieldBuilder() : null;
            } else {
              bdcBuilder_.addAllMessages(other.bdc_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        for (int i = 0; i < getBdcCount(); i++) {
          if (!getBdc(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.led.tools.proto.bmc.BmcInfo.Bmc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.led.tools.proto.bmc.BmcInfo.Bmc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required string ip = 2;
      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 2;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }

      // required string port = 3;
      private java.lang.Object port_ = "";
      /**
       * <code>required string port = 3;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string port = 3;</code>
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string port = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string port = 3;</code>
       */
      public Builder setPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string port = 3;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>required string port = 3;</code>
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }

      // optional string desc = 4;
      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 4;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }

      // repeated .bmc.Bmc.Bdc bdc = 5;
      private java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> bdc_ =
        java.util.Collections.emptyList();
      private void ensureBdcIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          bdc_ = new java.util.ArrayList<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc>(bdc_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder, org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder> bdcBuilder_;

      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> getBdcList() {
        if (bdcBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bdc_);
        } else {
          return bdcBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public int getBdcCount() {
        if (bdcBuilder_ == null) {
          return bdc_.size();
        } else {
          return bdcBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc getBdc(int index) {
        if (bdcBuilder_ == null) {
          return bdc_.get(index);
        } else {
          return bdcBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder setBdc(
          int index, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc value) {
        if (bdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBdcIsMutable();
          bdc_.set(index, value);
          onChanged();
        } else {
          bdcBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder setBdc(
          int index, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder builderForValue) {
        if (bdcBuilder_ == null) {
          ensureBdcIsMutable();
          bdc_.set(index, builderForValue.build());
          onChanged();
        } else {
          bdcBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder addBdc(org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc value) {
        if (bdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBdcIsMutable();
          bdc_.add(value);
          onChanged();
        } else {
          bdcBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder addBdc(
          int index, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc value) {
        if (bdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBdcIsMutable();
          bdc_.add(index, value);
          onChanged();
        } else {
          bdcBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder addBdc(
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder builderForValue) {
        if (bdcBuilder_ == null) {
          ensureBdcIsMutable();
          bdc_.add(builderForValue.build());
          onChanged();
        } else {
          bdcBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder addBdc(
          int index, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder builderForValue) {
        if (bdcBuilder_ == null) {
          ensureBdcIsMutable();
          bdc_.add(index, builderForValue.build());
          onChanged();
        } else {
          bdcBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder addAllBdc(
          java.lang.Iterable<? extends org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc> values) {
        if (bdcBuilder_ == null) {
          ensureBdcIsMutable();
          super.addAll(values, bdc_);
          onChanged();
        } else {
          bdcBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder clearBdc() {
        if (bdcBuilder_ == null) {
          bdc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          bdcBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public Builder removeBdc(int index) {
        if (bdcBuilder_ == null) {
          ensureBdcIsMutable();
          bdc_.remove(index);
          onChanged();
        } else {
          bdcBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder getBdcBuilder(
          int index) {
        return getBdcFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder getBdcOrBuilder(
          int index) {
        if (bdcBuilder_ == null) {
          return bdc_.get(index);  } else {
          return bdcBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public java.util.List<? extends org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder> 
           getBdcOrBuilderList() {
        if (bdcBuilder_ != null) {
          return bdcBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bdc_);
        }
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder addBdcBuilder() {
        return getBdcFieldBuilder().addBuilder(
            org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.getDefaultInstance());
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder addBdcBuilder(
          int index) {
        return getBdcFieldBuilder().addBuilder(
            index, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.getDefaultInstance());
      }
      /**
       * <code>repeated .bmc.Bmc.Bdc bdc = 5;</code>
       */
      public java.util.List<org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder> 
           getBdcBuilderList() {
        return getBdcFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder, org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder> 
          getBdcFieldBuilder() {
        if (bdcBuilder_ == null) {
          bdcBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc, org.led.tools.proto.bmc.BmcInfo.Bmc.Bdc.Builder, org.led.tools.proto.bmc.BmcInfo.Bmc.BdcOrBuilder>(
                  bdc_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          bdc_ = null;
        }
        return bdcBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:bmc.Bmc)
    }

    static {
      defaultInstance = new Bmc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bmc.Bmc)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bmc_Bmc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bmc_Bmc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bmc_Bmc_Bdc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bmc_Bmc_Bdc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbmc.proto\022\003bmc\"\223\001\n\003Bmc\022\014\n\004name\030\001 \002(\t\022\n" +
      "\n\002ip\030\002 \002(\t\022\014\n\004port\030\003 \002(\t\022\014\n\004desc\030\004 \001(\t\022\031" +
      "\n\003bdc\030\005 \003(\0132\014.bmc.Bmc.Bdc\032;\n\003Bdc\022\014\n\004name" +
      "\030\001 \002(\t\022\n\n\002ip\030\002 \002(\t\022\014\n\004port\030\003 \002(\t\022\014\n\004desc" +
      "\030\004 \001(\tB\026\n\013org.led.bmcB\007BmcInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bmc_Bmc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bmc_Bmc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bmc_Bmc_descriptor,
              new java.lang.String[] { "Name", "Ip", "Port", "Desc", "Bdc", });
          internal_static_bmc_Bmc_Bdc_descriptor =
            internal_static_bmc_Bmc_descriptor.getNestedTypes().get(0);
          internal_static_bmc_Bmc_Bdc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bmc_Bmc_Bdc_descriptor,
              new java.lang.String[] { "Name", "Ip", "Port", "Desc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
