/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.led.sreporting.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ReceptionReport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReceptionReport\",\"namespace\":\"org.led.sreporting.avro\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"serviceId\",\"type\":\"string\"},{\"name\":\"serviceURI\",\"type\":\"string\"},{\"name\":\"sessionType\",\"type\":\"string\"},{\"name\":\"sessionStartTime\",\"type\":\"long\"},{\"name\":\"sessionStopTime\",\"type\":\"long\"},{\"name\":\"networkResourceCellId\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"sessionId\",\"type\":\"string\"},{\"name\":\"deliverySessionInstanceInfoId\",\"type\":\"long\"},{\"name\":\"numOfLostObjects\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"numOfReceivedObjects\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"FileUriList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"FileUriRec\",\"fields\":[{\"name\":\"fileURI\",\"type\":\"string\"},{\"name\":\"receptionSuccess\",\"type\":\"boolean\"},{\"name\":\"ContentMD5\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence clientId;
  @Deprecated public java.lang.CharSequence serviceId;
  @Deprecated public java.lang.CharSequence serviceURI;
  @Deprecated public java.lang.CharSequence sessionType;
  @Deprecated public long sessionStartTime;
  @Deprecated public long sessionStopTime;
  @Deprecated public java.util.List<java.lang.CharSequence> networkResourceCellId;
  @Deprecated public java.lang.CharSequence sessionId;
  @Deprecated public long deliverySessionInstanceInfoId;
  @Deprecated public java.util.List<java.lang.Integer> numOfLostObjects;
  @Deprecated public java.util.List<java.lang.Integer> numOfReceivedObjects;
  @Deprecated public java.util.List<org.led.sreporting.avro.FileUriRec> FileUriList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ReceptionReport() {}

  /**
   * All-args constructor.
   */
  public ReceptionReport(java.lang.CharSequence clientId, java.lang.CharSequence serviceId, java.lang.CharSequence serviceURI, java.lang.CharSequence sessionType, java.lang.Long sessionStartTime, java.lang.Long sessionStopTime, java.util.List<java.lang.CharSequence> networkResourceCellId, java.lang.CharSequence sessionId, java.lang.Long deliverySessionInstanceInfoId, java.util.List<java.lang.Integer> numOfLostObjects, java.util.List<java.lang.Integer> numOfReceivedObjects, java.util.List<org.led.sreporting.avro.FileUriRec> FileUriList) {
    this.clientId = clientId;
    this.serviceId = serviceId;
    this.serviceURI = serviceURI;
    this.sessionType = sessionType;
    this.sessionStartTime = sessionStartTime;
    this.sessionStopTime = sessionStopTime;
    this.networkResourceCellId = networkResourceCellId;
    this.sessionId = sessionId;
    this.deliverySessionInstanceInfoId = deliverySessionInstanceInfoId;
    this.numOfLostObjects = numOfLostObjects;
    this.numOfReceivedObjects = numOfReceivedObjects;
    this.FileUriList = FileUriList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientId;
    case 1: return serviceId;
    case 2: return serviceURI;
    case 3: return sessionType;
    case 4: return sessionStartTime;
    case 5: return sessionStopTime;
    case 6: return networkResourceCellId;
    case 7: return sessionId;
    case 8: return deliverySessionInstanceInfoId;
    case 9: return numOfLostObjects;
    case 10: return numOfReceivedObjects;
    case 11: return FileUriList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientId = (java.lang.CharSequence)value$; break;
    case 1: serviceId = (java.lang.CharSequence)value$; break;
    case 2: serviceURI = (java.lang.CharSequence)value$; break;
    case 3: sessionType = (java.lang.CharSequence)value$; break;
    case 4: sessionStartTime = (java.lang.Long)value$; break;
    case 5: sessionStopTime = (java.lang.Long)value$; break;
    case 6: networkResourceCellId = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: sessionId = (java.lang.CharSequence)value$; break;
    case 8: deliverySessionInstanceInfoId = (java.lang.Long)value$; break;
    case 9: numOfLostObjects = (java.util.List<java.lang.Integer>)value$; break;
    case 10: numOfReceivedObjects = (java.util.List<java.lang.Integer>)value$; break;
    case 11: FileUriList = (java.util.List<org.led.sreporting.avro.FileUriRec>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'clientId' field.
   */
  public java.lang.CharSequence getClientId() {
    return clientId;
  }

  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.CharSequence value) {
    this.clientId = value;
  }

  /**
   * Gets the value of the 'serviceId' field.
   */
  public java.lang.CharSequence getServiceId() {
    return serviceId;
  }

  /**
   * Sets the value of the 'serviceId' field.
   * @param value the value to set.
   */
  public void setServiceId(java.lang.CharSequence value) {
    this.serviceId = value;
  }

  /**
   * Gets the value of the 'serviceURI' field.
   */
  public java.lang.CharSequence getServiceURI() {
    return serviceURI;
  }

  /**
   * Sets the value of the 'serviceURI' field.
   * @param value the value to set.
   */
  public void setServiceURI(java.lang.CharSequence value) {
    this.serviceURI = value;
  }

  /**
   * Gets the value of the 'sessionType' field.
   */
  public java.lang.CharSequence getSessionType() {
    return sessionType;
  }

  /**
   * Sets the value of the 'sessionType' field.
   * @param value the value to set.
   */
  public void setSessionType(java.lang.CharSequence value) {
    this.sessionType = value;
  }

  /**
   * Gets the value of the 'sessionStartTime' field.
   */
  public java.lang.Long getSessionStartTime() {
    return sessionStartTime;
  }

  /**
   * Sets the value of the 'sessionStartTime' field.
   * @param value the value to set.
   */
  public void setSessionStartTime(java.lang.Long value) {
    this.sessionStartTime = value;
  }

  /**
   * Gets the value of the 'sessionStopTime' field.
   */
  public java.lang.Long getSessionStopTime() {
    return sessionStopTime;
  }

  /**
   * Sets the value of the 'sessionStopTime' field.
   * @param value the value to set.
   */
  public void setSessionStopTime(java.lang.Long value) {
    this.sessionStopTime = value;
  }

  /**
   * Gets the value of the 'networkResourceCellId' field.
   */
  public java.util.List<java.lang.CharSequence> getNetworkResourceCellId() {
    return networkResourceCellId;
  }

  /**
   * Sets the value of the 'networkResourceCellId' field.
   * @param value the value to set.
   */
  public void setNetworkResourceCellId(java.util.List<java.lang.CharSequence> value) {
    this.networkResourceCellId = value;
  }

  /**
   * Gets the value of the 'sessionId' field.
   */
  public java.lang.CharSequence getSessionId() {
    return sessionId;
  }

  /**
   * Sets the value of the 'sessionId' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.CharSequence value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'deliverySessionInstanceInfoId' field.
   */
  public java.lang.Long getDeliverySessionInstanceInfoId() {
    return deliverySessionInstanceInfoId;
  }

  /**
   * Sets the value of the 'deliverySessionInstanceInfoId' field.
   * @param value the value to set.
   */
  public void setDeliverySessionInstanceInfoId(java.lang.Long value) {
    this.deliverySessionInstanceInfoId = value;
  }

  /**
   * Gets the value of the 'numOfLostObjects' field.
   */
  public java.util.List<java.lang.Integer> getNumOfLostObjects() {
    return numOfLostObjects;
  }

  /**
   * Sets the value of the 'numOfLostObjects' field.
   * @param value the value to set.
   */
  public void setNumOfLostObjects(java.util.List<java.lang.Integer> value) {
    this.numOfLostObjects = value;
  }

  /**
   * Gets the value of the 'numOfReceivedObjects' field.
   */
  public java.util.List<java.lang.Integer> getNumOfReceivedObjects() {
    return numOfReceivedObjects;
  }

  /**
   * Sets the value of the 'numOfReceivedObjects' field.
   * @param value the value to set.
   */
  public void setNumOfReceivedObjects(java.util.List<java.lang.Integer> value) {
    this.numOfReceivedObjects = value;
  }

  /**
   * Gets the value of the 'FileUriList' field.
   */
  public java.util.List<org.led.sreporting.avro.FileUriRec> getFileUriList() {
    return FileUriList;
  }

  /**
   * Sets the value of the 'FileUriList' field.
   * @param value the value to set.
   */
  public void setFileUriList(java.util.List<org.led.sreporting.avro.FileUriRec> value) {
    this.FileUriList = value;
  }

  /** Creates a new ReceptionReport RecordBuilder */
  public static org.led.sreporting.avro.ReceptionReport.Builder newBuilder() {
    return new org.led.sreporting.avro.ReceptionReport.Builder();
  }
  
  /** Creates a new ReceptionReport RecordBuilder by copying an existing Builder */
  public static org.led.sreporting.avro.ReceptionReport.Builder newBuilder(org.led.sreporting.avro.ReceptionReport.Builder other) {
    return new org.led.sreporting.avro.ReceptionReport.Builder(other);
  }
  
  /** Creates a new ReceptionReport RecordBuilder by copying an existing ReceptionReport instance */
  public static org.led.sreporting.avro.ReceptionReport.Builder newBuilder(org.led.sreporting.avro.ReceptionReport other) {
    return new org.led.sreporting.avro.ReceptionReport.Builder(other);
  }
  
  /**
   * RecordBuilder for ReceptionReport instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReceptionReport>
    implements org.apache.avro.data.RecordBuilder<ReceptionReport> {

    private java.lang.CharSequence clientId;
    private java.lang.CharSequence serviceId;
    private java.lang.CharSequence serviceURI;
    private java.lang.CharSequence sessionType;
    private long sessionStartTime;
    private long sessionStopTime;
    private java.util.List<java.lang.CharSequence> networkResourceCellId;
    private java.lang.CharSequence sessionId;
    private long deliverySessionInstanceInfoId;
    private java.util.List<java.lang.Integer> numOfLostObjects;
    private java.util.List<java.lang.Integer> numOfReceivedObjects;
    private java.util.List<org.led.sreporting.avro.FileUriRec> FileUriList;

    /** Creates a new Builder */
    private Builder() {
      super(org.led.sreporting.avro.ReceptionReport.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.led.sreporting.avro.ReceptionReport.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[1].schema(), other.serviceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serviceURI)) {
        this.serviceURI = data().deepCopy(fields()[2].schema(), other.serviceURI);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sessionType)) {
        this.sessionType = data().deepCopy(fields()[3].schema(), other.sessionType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sessionStartTime)) {
        this.sessionStartTime = data().deepCopy(fields()[4].schema(), other.sessionStartTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sessionStopTime)) {
        this.sessionStopTime = data().deepCopy(fields()[5].schema(), other.sessionStopTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.networkResourceCellId)) {
        this.networkResourceCellId = data().deepCopy(fields()[6].schema(), other.networkResourceCellId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[7].schema(), other.sessionId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deliverySessionInstanceInfoId)) {
        this.deliverySessionInstanceInfoId = data().deepCopy(fields()[8].schema(), other.deliverySessionInstanceInfoId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.numOfLostObjects)) {
        this.numOfLostObjects = data().deepCopy(fields()[9].schema(), other.numOfLostObjects);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.numOfReceivedObjects)) {
        this.numOfReceivedObjects = data().deepCopy(fields()[10].schema(), other.numOfReceivedObjects);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.FileUriList)) {
        this.FileUriList = data().deepCopy(fields()[11].schema(), other.FileUriList);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ReceptionReport instance */
    private Builder(org.led.sreporting.avro.ReceptionReport other) {
            super(org.led.sreporting.avro.ReceptionReport.SCHEMA$);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[1].schema(), other.serviceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serviceURI)) {
        this.serviceURI = data().deepCopy(fields()[2].schema(), other.serviceURI);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sessionType)) {
        this.sessionType = data().deepCopy(fields()[3].schema(), other.sessionType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sessionStartTime)) {
        this.sessionStartTime = data().deepCopy(fields()[4].schema(), other.sessionStartTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sessionStopTime)) {
        this.sessionStopTime = data().deepCopy(fields()[5].schema(), other.sessionStopTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.networkResourceCellId)) {
        this.networkResourceCellId = data().deepCopy(fields()[6].schema(), other.networkResourceCellId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[7].schema(), other.sessionId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deliverySessionInstanceInfoId)) {
        this.deliverySessionInstanceInfoId = data().deepCopy(fields()[8].schema(), other.deliverySessionInstanceInfoId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.numOfLostObjects)) {
        this.numOfLostObjects = data().deepCopy(fields()[9].schema(), other.numOfLostObjects);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.numOfReceivedObjects)) {
        this.numOfReceivedObjects = data().deepCopy(fields()[10].schema(), other.numOfReceivedObjects);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.FileUriList)) {
        this.FileUriList = data().deepCopy(fields()[11].schema(), other.FileUriList);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'clientId' field */
    public java.lang.CharSequence getClientId() {
      return clientId;
    }
    
    /** Sets the value of the 'clientId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setClientId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.clientId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'clientId' field has been set */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'clientId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearClientId() {
      clientId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'serviceId' field */
    public java.lang.CharSequence getServiceId() {
      return serviceId;
    }
    
    /** Sets the value of the 'serviceId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setServiceId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serviceId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'serviceId' field has been set */
    public boolean hasServiceId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'serviceId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearServiceId() {
      serviceId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'serviceURI' field */
    public java.lang.CharSequence getServiceURI() {
      return serviceURI;
    }
    
    /** Sets the value of the 'serviceURI' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setServiceURI(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.serviceURI = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'serviceURI' field has been set */
    public boolean hasServiceURI() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'serviceURI' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearServiceURI() {
      serviceURI = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'sessionType' field */
    public java.lang.CharSequence getSessionType() {
      return sessionType;
    }
    
    /** Sets the value of the 'sessionType' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setSessionType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sessionType = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'sessionType' field has been set */
    public boolean hasSessionType() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'sessionType' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearSessionType() {
      sessionType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'sessionStartTime' field */
    public java.lang.Long getSessionStartTime() {
      return sessionStartTime;
    }
    
    /** Sets the value of the 'sessionStartTime' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setSessionStartTime(long value) {
      validate(fields()[4], value);
      this.sessionStartTime = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'sessionStartTime' field has been set */
    public boolean hasSessionStartTime() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'sessionStartTime' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearSessionStartTime() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'sessionStopTime' field */
    public java.lang.Long getSessionStopTime() {
      return sessionStopTime;
    }
    
    /** Sets the value of the 'sessionStopTime' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setSessionStopTime(long value) {
      validate(fields()[5], value);
      this.sessionStopTime = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'sessionStopTime' field has been set */
    public boolean hasSessionStopTime() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'sessionStopTime' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearSessionStopTime() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'networkResourceCellId' field */
    public java.util.List<java.lang.CharSequence> getNetworkResourceCellId() {
      return networkResourceCellId;
    }
    
    /** Sets the value of the 'networkResourceCellId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setNetworkResourceCellId(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.networkResourceCellId = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'networkResourceCellId' field has been set */
    public boolean hasNetworkResourceCellId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'networkResourceCellId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearNetworkResourceCellId() {
      networkResourceCellId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'sessionId' field */
    public java.lang.CharSequence getSessionId() {
      return sessionId;
    }
    
    /** Sets the value of the 'sessionId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setSessionId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.sessionId = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'sessionId' field has been set */
    public boolean hasSessionId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'sessionId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'deliverySessionInstanceInfoId' field */
    public java.lang.Long getDeliverySessionInstanceInfoId() {
      return deliverySessionInstanceInfoId;
    }
    
    /** Sets the value of the 'deliverySessionInstanceInfoId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setDeliverySessionInstanceInfoId(long value) {
      validate(fields()[8], value);
      this.deliverySessionInstanceInfoId = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'deliverySessionInstanceInfoId' field has been set */
    public boolean hasDeliverySessionInstanceInfoId() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'deliverySessionInstanceInfoId' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearDeliverySessionInstanceInfoId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'numOfLostObjects' field */
    public java.util.List<java.lang.Integer> getNumOfLostObjects() {
      return numOfLostObjects;
    }
    
    /** Sets the value of the 'numOfLostObjects' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setNumOfLostObjects(java.util.List<java.lang.Integer> value) {
      validate(fields()[9], value);
      this.numOfLostObjects = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'numOfLostObjects' field has been set */
    public boolean hasNumOfLostObjects() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'numOfLostObjects' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearNumOfLostObjects() {
      numOfLostObjects = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'numOfReceivedObjects' field */
    public java.util.List<java.lang.Integer> getNumOfReceivedObjects() {
      return numOfReceivedObjects;
    }
    
    /** Sets the value of the 'numOfReceivedObjects' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setNumOfReceivedObjects(java.util.List<java.lang.Integer> value) {
      validate(fields()[10], value);
      this.numOfReceivedObjects = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'numOfReceivedObjects' field has been set */
    public boolean hasNumOfReceivedObjects() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'numOfReceivedObjects' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearNumOfReceivedObjects() {
      numOfReceivedObjects = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'FileUriList' field */
    public java.util.List<org.led.sreporting.avro.FileUriRec> getFileUriList() {
      return FileUriList;
    }
    
    /** Sets the value of the 'FileUriList' field */
    public org.led.sreporting.avro.ReceptionReport.Builder setFileUriList(java.util.List<org.led.sreporting.avro.FileUriRec> value) {
      validate(fields()[11], value);
      this.FileUriList = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'FileUriList' field has been set */
    public boolean hasFileUriList() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'FileUriList' field */
    public org.led.sreporting.avro.ReceptionReport.Builder clearFileUriList() {
      FileUriList = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public ReceptionReport build() {
      try {
        ReceptionReport record = new ReceptionReport();
        record.clientId = fieldSetFlags()[0] ? this.clientId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.serviceId = fieldSetFlags()[1] ? this.serviceId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.serviceURI = fieldSetFlags()[2] ? this.serviceURI : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sessionType = fieldSetFlags()[3] ? this.sessionType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.sessionStartTime = fieldSetFlags()[4] ? this.sessionStartTime : (java.lang.Long) defaultValue(fields()[4]);
        record.sessionStopTime = fieldSetFlags()[5] ? this.sessionStopTime : (java.lang.Long) defaultValue(fields()[5]);
        record.networkResourceCellId = fieldSetFlags()[6] ? this.networkResourceCellId : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.sessionId = fieldSetFlags()[7] ? this.sessionId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.deliverySessionInstanceInfoId = fieldSetFlags()[8] ? this.deliverySessionInstanceInfoId : (java.lang.Long) defaultValue(fields()[8]);
        record.numOfLostObjects = fieldSetFlags()[9] ? this.numOfLostObjects : (java.util.List<java.lang.Integer>) defaultValue(fields()[9]);
        record.numOfReceivedObjects = fieldSetFlags()[10] ? this.numOfReceivedObjects : (java.util.List<java.lang.Integer>) defaultValue(fields()[10]);
        record.FileUriList = fieldSetFlags()[11] ? this.FileUriList : (java.util.List<org.led.sreporting.avro.FileUriRec>) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
