/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.led.bigdata.sparkavro.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FileUriRec extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FileUriRec\",\"namespace\":\"org.led.sreporting.avro\",\"fields\":[{\"name\":\"fileURI\",\"type\":\"string\"},{\"name\":\"receptionSuccess\",\"type\":\"boolean\"},{\"name\":\"ContentMD5\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence fileURI;
  @Deprecated public boolean receptionSuccess;
  @Deprecated public java.lang.CharSequence ContentMD5;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public FileUriRec() {}

  /**
   * All-args constructor.
   */
  public FileUriRec(java.lang.CharSequence fileURI, java.lang.Boolean receptionSuccess, java.lang.CharSequence ContentMD5) {
    this.fileURI = fileURI;
    this.receptionSuccess = receptionSuccess;
    this.ContentMD5 = ContentMD5;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileURI;
    case 1: return receptionSuccess;
    case 2: return ContentMD5;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileURI = (java.lang.CharSequence)value$; break;
    case 1: receptionSuccess = (java.lang.Boolean)value$; break;
    case 2: ContentMD5 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fileURI' field.
   */
  public java.lang.CharSequence getFileURI() {
    return fileURI;
  }

  /**
   * Sets the value of the 'fileURI' field.
   * @param value the value to set.
   */
  public void setFileURI(java.lang.CharSequence value) {
    this.fileURI = value;
  }

  /**
   * Gets the value of the 'receptionSuccess' field.
   */
  public java.lang.Boolean getReceptionSuccess() {
    return receptionSuccess;
  }

  /**
   * Sets the value of the 'receptionSuccess' field.
   * @param value the value to set.
   */
  public void setReceptionSuccess(java.lang.Boolean value) {
    this.receptionSuccess = value;
  }

  /**
   * Gets the value of the 'ContentMD5' field.
   */
  public java.lang.CharSequence getContentMD5() {
    return ContentMD5;
  }

  /**
   * Sets the value of the 'ContentMD5' field.
   * @param value the value to set.
   */
  public void setContentMD5(java.lang.CharSequence value) {
    this.ContentMD5 = value;
  }

  /** Creates a new FileUriRec RecordBuilder */
  public static org.led.bigdata.sparkavro.avro.FileUriRec.Builder newBuilder() {
    return new org.led.bigdata.sparkavro.avro.FileUriRec.Builder();
  }
  
  /** Creates a new FileUriRec RecordBuilder by copying an existing Builder */
  public static org.led.bigdata.sparkavro.avro.FileUriRec.Builder newBuilder(org.led.bigdata.sparkavro.avro.FileUriRec.Builder other) {
    return new org.led.bigdata.sparkavro.avro.FileUriRec.Builder(other);
  }
  
  /** Creates a new FileUriRec RecordBuilder by copying an existing FileUriRec instance */
  public static org.led.bigdata.sparkavro.avro.FileUriRec.Builder newBuilder(org.led.bigdata.sparkavro.avro.FileUriRec other) {
    return new org.led.bigdata.sparkavro.avro.FileUriRec.Builder(other);
  }
  
  /**
   * RecordBuilder for FileUriRec instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FileUriRec>
    implements org.apache.avro.data.RecordBuilder<FileUriRec> {

    private java.lang.CharSequence fileURI;
    private boolean receptionSuccess;
    private java.lang.CharSequence ContentMD5;

    /** Creates a new Builder */
    private Builder() {
      super(org.led.bigdata.sparkavro.avro.FileUriRec.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.led.bigdata.sparkavro.avro.FileUriRec.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileURI)) {
        this.fileURI = data().deepCopy(fields()[0].schema(), other.fileURI);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receptionSuccess)) {
        this.receptionSuccess = data().deepCopy(fields()[1].schema(), other.receptionSuccess);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ContentMD5)) {
        this.ContentMD5 = data().deepCopy(fields()[2].schema(), other.ContentMD5);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing FileUriRec instance */
    private Builder(org.led.bigdata.sparkavro.avro.FileUriRec other) {
            super(org.led.bigdata.sparkavro.avro.FileUriRec.SCHEMA$);
      if (isValidValue(fields()[0], other.fileURI)) {
        this.fileURI = data().deepCopy(fields()[0].schema(), other.fileURI);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receptionSuccess)) {
        this.receptionSuccess = data().deepCopy(fields()[1].schema(), other.receptionSuccess);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ContentMD5)) {
        this.ContentMD5 = data().deepCopy(fields()[2].schema(), other.ContentMD5);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'fileURI' field */
    public java.lang.CharSequence getFileURI() {
      return fileURI;
    }
    
    /** Sets the value of the 'fileURI' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder setFileURI(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fileURI = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'fileURI' field has been set */
    public boolean hasFileURI() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'fileURI' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder clearFileURI() {
      fileURI = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'receptionSuccess' field */
    public java.lang.Boolean getReceptionSuccess() {
      return receptionSuccess;
    }
    
    /** Sets the value of the 'receptionSuccess' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder setReceptionSuccess(boolean value) {
      validate(fields()[1], value);
      this.receptionSuccess = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'receptionSuccess' field has been set */
    public boolean hasReceptionSuccess() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'receptionSuccess' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder clearReceptionSuccess() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ContentMD5' field */
    public java.lang.CharSequence getContentMD5() {
      return ContentMD5;
    }
    
    /** Sets the value of the 'ContentMD5' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder setContentMD5(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ContentMD5 = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ContentMD5' field has been set */
    public boolean hasContentMD5() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ContentMD5' field */
    public org.led.bigdata.sparkavro.avro.FileUriRec.Builder clearContentMD5() {
      ContentMD5 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public FileUriRec build() {
      try {
        FileUriRec record = new FileUriRec();
        record.fileURI = fieldSetFlags()[0] ? this.fileURI : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.receptionSuccess = fieldSetFlags()[1] ? this.receptionSuccess : (java.lang.Boolean) defaultValue(fields()[1]);
        record.ContentMD5 = fieldSetFlags()[2] ? this.ContentMD5 : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
